name: Set up, deploy and test local subgraph

on:
  workflow_call:
    inputs:
      is-subgraph-package-tests:
        required: true
        type: boolean
      subgraph-release:
        required: false
        type: string

jobs:
  setup-and-test-subgraph:
    name: Build and test subgraph

    runs-on: ubuntu-latest

    env:
      contracts-working-directory: ./packages/ethereum-contracts

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install packages and start hardhat node"
        run: |
          yarn install
          ./tasks/startHardhatNode.sh start
        working-directory: ./packages/sdk-core

      - name: "Checkout graph node repo and set up local graph node"
        uses: actions/checkout@v3
        with:
          repository: graphprotocol/graph-node
          path: graph-node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run setup because linux and docker-compose"
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          chmod +x setup.sh
          ./setup.sh
        working-directory: ./graph-node/docker

      - name: "Docker compose"
        run: docker-compose up &
        working-directory: ./graph-node/docker

      - name: "Run subgraph integration test suite"
        if: ${{ inputs.is-subgraph-package-tests }}
        run: yarn test
        working-directory: ./packages/subgraph

      # test local subgraph w/ SDK-core
      - name: "Install contract dependencies"
        if: ${{ !inputs.is-subgraph-package-tests }}
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        if: ${{ !inputs.is-subgraph-package-tests }}
        run: yarn run build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Run SDK-Core tests and test subgraph query with local subgraph"
        if: ${{ !inputs.is-subgraph-package-tests }}
        run: |
          yarn generate-graphql-schema:${{ inputs.subgraph-release }}
          ./tasks/setupTestEnvironment.sh
          npx hardhat test
        working-directory: ./packages/sdk-core
        env: 
          LOCAL_SUBGRAPH_URL: http://localhost:8000/subgraphs/name/superfluid-test