mame:

on:
  workflow_call:
    inputs:
      subgraph-release:
        required: true
        type: string
# ADD THIS TO canary + before subgraph deploy script as well
jobs:
  build-and-test-live-subgraph-previous-releases:
    name: Build and test current subgraph release with previous sdk-core versions

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [0.3.2, 0.4.0, 0.4.1]

    env:
      contracts-working-directory: ./packages/ethereum-contracts
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: "Install contract dependencies"
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Install packages and test"
        run: |
          yarn install
          ./tasks/startHardhatNode.sh start
          ./tasks/setupTestEnvironment.sh
        working-directory: ./packages/sdk-core

      - name: "Install @superfluid-finance/sdk-core@${{ matrix.version}} and test subgraph queries"
        run: |
          yarn add -D @superfluid-finance/sdk-core@v${{ matrix.version }}
          yarn run-query-tests
          ./tasks/startHardhatNode.sh stop
        working-directory: ./packages/sdk-core/previous-versions-testing