name: Pre-Release Draft SDK Core-Subgraph Integration Test

on:
  pull_request:
    branches:
      - "release-subgraph-v1"
      - "release-sdk-core-stable"
    paths:
      - "packages/subgraph/**"
      - "packages/sdk-core/**"
      - ".github/workflows/ci.pre-release-draft-test-sdk-core-subgraph-integration.yml"

jobs:
  show-contexts:
    name: Show Contexts

    runs-on: ubuntu-latest

    steps:
      - name: Show contexts
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

  build-and-test-local-subgraph:
    uses: superfluid-finance/protocol-monorepo/.github/workflows/call.setup-and-deploy-local-subgraph.yml@sdk-core-subgraph-query-test
    name: Build and Test Subgraph (Release Branch)
    with:
      is-subgraph-package-tests: true
      subgraph-release: v1

  # build and test live subgraph with release sdk-core
  build-and-test-live-subgraph-current-release:
    uses: superfluid-finance/protocol-monorepo/.github/workflows/call.test-sdk-core.yml@sdk-core-subgraph-query-test
    name: Build and Test SDK-Core (Release branch)
    if: github.base_ref == "release-sdk-core-stable"
    with:
      subgraph-release: v1

  # build and test live subgraph with previous sdk-core releases
  build-and-test-live-subgraph-previous-releases:
    name: Build and test previous sdk-core versions with current subgraph release

    runs-on: ubuntu-latest

    if: github.base_ref == "release-subgraph-v1"

    matrix:
      version: [0.3.2, 0.4.0, 0.4.1]

    env:
      env.contracts-working-directory: ./packages/ethereum-contracts
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: "Install contract dependencies"
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn run build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Install packages and test"
        run: |
          yarn install
          ./tasks/startHardhatNode.sh start
          ./tasks/setupTestEnvironment.sh
        working-directory: ./packages/sdk-core

      - name: "Install @superfluid-finance/sdk-core@${{ matrix.version}} and test subgraph queries"
        run: |
          yarn add -D @superfluid-finance/sdk-core@v${{ matrix.version }}
          yarn run-query-tests
          ./tasks/startHardhatNode.sh stop
        working-directory: ./packages/sdk-core/previous-versions-testing