name: Pre-Release Draft SDK Core-Subgraph Integration Test

on:
  push:

  pull_request:
    branches:
      - "release-subgraph-v1"
      - "release-sdk-core-stable"
    paths:
      - "packages/subgraph/**"
      - "packages/sdk-core/**"
      - ".github/workflows/ci.pre-release-draft-test-sdk-core-subgraph-integration.yml"

jobs:
  show-contexts:
    name: Show Contexts

    runs-on: ubuntu-latest

    steps:
      - name: Show contexts
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

  build-and-test-local-subgraph:
    uses: superfluid-finance/protocol-monorepo/.github/workflows/call.setup-and-deploy-local-subgraph.yml@sdk-core-subgraph-query-test
    name: Build and Test Subgraph (Release Branch)
    with:
      is-subgraph-package-tests: true
      subgraph-release: v1

  # build and test live subgraph with release sdk-core
  build-and-test-live-subgraph-current-release:
    uses: superfluid-finance/protocol-monorepo/.github/workflows/call.test-sdk-core.yml@sdk-core-subgraph-query-test
    name: Build and Test SDK-Core (Release branch)
    if: github.base_ref == 'release-sdk-core-stable'
    with:
      subgraph-release: v1

  # build and test live subgraph with previous sdk-core releases
  build-and-test-live-subgraph-previous-releases:
    uses: superfluid-finance/protocol-monorepo/.github/workflows/call.test-sdk-core.yml@sdk-core-subgraph-query-test
    name: Build and test current subgraph release with previous sdk-core versions
    if: github.base_ref == 'release-subgraph-v1'
    with:
      subgraph-release: v1